from typing import List, Optional, TypedDict
from pydantic import BaseModel, Field

# Graph State
class TicketState(TypedDict):
    ticket_id: str
    ticket_text: str
    order_context: dict
    
    # Generated by Triage Agent
    classification: str
    clarifying_questions: List[str]
    missing_critical_info: bool
    
    # Generated by Retriever Agent
    retrieved_chunks: List[dict] # list of {"content": str, "metadata": dict}
    
    # Generated by Writer Agent
    draft_response: str
    decision: str
    rationale: str
    citations: List[str]
    next_steps: str
    
    # Generated by Compliance Agent
    compliance_passed: bool
    iterations: int

# Pydantic Output parsers for LLMs
class TriageOutput(BaseModel):
    classification: str = Field(description="Issue type: refund, shipping, payment, promo, fraud, return, dispute, or other")
    missing_critical_info: bool = Field(description="True if critical fields like order number or item name are missing and required to resolve the ticket")
    clarifying_questions: List[str] = Field(description="Up to 3 clarifying questions if there is missing or ambiguous information. Empty list if none needed.", default_factory=list)

class WriterOutput(BaseModel):
    decision: str = Field(description="Decision: approve, deny, partial, or needs_escalation")
    rationale: str = Field(description="Policy-based explanation for the decision")
    citations: List[str] = Field(description="Bullet list of citations (document title + section/chunk id) that exclusively back up the rationale")
    draft_response: str = Field(description="Customer-ready message addressing their issue according to guidelines")
    next_steps: str = Field(description="What the agent recommends support does next internally")

class ComplianceOutput(BaseModel):
    passed: bool = Field(description="True if the draft response is grounded in policy, safe, and has proper citations. False otherwise.")
    feedback: str = Field(description="Feedback on what is unsupported, missing, or hallucinated. Empty if passed.", default="")
